[workspace]
members = [
    "codegen",
    "examples/bevy_2048",
    "ffi",
    "images/*",
    "proc_blocks/*",
    "python",
    "rune",
    "runic-types",
    "runtime",
    "syntax",
    "xtask",
    "wasmer-runtime",
]
