name: Continuous integration

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  check:
    name: Compile and Test
    strategy:
      matrix:
        os:
          - ubuntu-18.04
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            python/target
          key: ${{ runner.os }}-${{ github.workflow }}-${{ github.job }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Update Rustup
        run: |
          # We need to update rustup because the mac version is out of date and
          # self-update is disabled. https://github.com/rust-lang/rustup/issues/2766
          curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain none -y
        if: runner.os == 'macOS'
      - name: Setup Rust
        run: rustup show
      # We need to explicitly install clang and record where libclang is
      # https://github.com/rust-lang/rust-bindgen/issues/1797
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "11.0"
          directory: ${{ runner.temp }}/llvm
        if: runner.os == 'Windows'
      - name: Set LIBCLANG_PATH
        run: echo "LIBCLANG_PATH=$((gcm clang).source -replace "clang.exe")" >> $env:GITHUB_ENV
        if: runner.os == 'Windows'
      - name: Type Check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --workspace --verbose --locked
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --workspace --verbose --locked
      - name: Unit Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --verbose --locked
      - name: Integration Tests
        uses: actions-rs/cargo@v1
        with:
          command: integration-tests

  api-docs:
    name: Generate API Docs
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ github.workflow }}-${{ github.job }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Update Rustup
        run: |
          # We need to update rustup because the mac version is out of date and
          # self-update is disabled. https://github.com/rust-lang/rustup/issues/2766
          curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain none -y
        if: runner.os == 'macOS'
      - name: Setup Rust
        run: rustup show
      - name: Generate API Docs
        id: first_try
        uses: actions-rs/cargo@v1
        continue-on-error: true
        with:
          command: doc
          args: --workspace --verbose --locked
      # Sometimes generating docs on GitHub actions will spuriously fail with
      # a random "file not found" error - possibly due to caching.
      #
      #   error: failed to remove file `/home/runner/work/rune/rune/target/doc/rune/constant.DEFAULT_RUST_LOG.html`
      #   Caused by:
      #      No such file or directory (os error 2)
      - name: Generate API Docs (second attempt)
        run: |
          cargo clean --doc
          cargo doc --workspace --verbose --locked
        if: ${{ steps.first_try.outcome == 'failure' }}
      - name: Automatically redirect to rune_runtime docs
        run: echo '<meta http-equiv="refresh" content="0; url=rune_runtime/index.html" />' > target/doc/index.html
      - name: Upload API Docs
        uses: JamesIves/github-pages-deploy-action@4.1.1
        if: github.ref == 'refs/heads/master'
        with:
          branch: gh-pages
          folder: target/doc
